services:
  app:
    image: pytest-sample:1.0
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
        WORKDIR: ${WORKDIR}
        PYTHON_IMAGE_TAG: ${PYTHON_IMAGE_TAG}
    volumes:
      - ./:${WORKDIR}
    restart: always
    environment:
      - TZ=${TZ}
    tty: true
