name: Python test udm

on : [push, pull_request]

jobs: 
  pytest:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Set up Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt; fi

      - name: ADD PYTHONPATH
        run : echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          python -m pytest
        continue-on-error: true